language: python
    - "2.7"

install:
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - pip install --user --upgrade google-api-python-client

script:
    - ./build/test
